name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
template: |
  # What's Changed

  $CHANGES

  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION

  $CONTRIBUTORS

categories:
  - title: '✨ Features'
    labels:
      - '✨ Feature'
      - '🎨 UI'
  - title: '🐛 Bug Fixes'
    labels:
      - '🐛 Bug'
  - title: '🔧 Refactoring'
    labels:
      - '🔧 Refactor'
  - title: '👏 ETC'
    label: '⚙️ Chore'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
